### ISSUE TITLE
Integer bad encoding

### ISSUE THREAD

**Issue by heretic13** [benjreinhart/bencode-js#9]
console.log(Bencode.encode(2436043716));

**Comment by heretic13** [comment]
file: bencode.js

case !(typeof object === 'number'):
        return encodeInteger(0 | object);

operator '|' interpret values as 32-bit integers.

**Comment by jeremybanks** [comment]
Yeah, just ran into this myself (after this was the first result when trying to find a library to hack something together with). It's casting to integer using `| 0` which truncates to 32 bits, but lots of torrent files describe sizes larger than that.

Replacing it with `parseInt(n, 10)` or something like that would probably do that job without error.
